// import Footer from "@/components/shared/Footer";
import Footer from '../components/shared/Footer';
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
// import Navigation from "@/components/shared/Navigation";
import Navigation from '../components/shared/Navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Navigation ></Navigation>
        {children}
        <Footer />
      </body>
    </html>
  );
}
